kind: pipeline
name: default
steps:
  - name: restore
    image: plugins/s3-cache
    settings:
      restore: true
      root: securedocs-drone-build-cache
  - name: echo
    image: alpine
    commands:
      - cat cache/new-file || echo Not found
      - mkdir -p cache
      - echo 'file contents' > cache/new-file
      - echo "I ran"
  - name: rebuild
    image: plugins/s3-cache
    settings:
      rebuild: true
      root: securedocs-drone-build-cache
      mount:
        - cache
