kind: pipeline
name: default
steps:
  - name: echo
    image: alpine
    commands:
      - echo "I should run, but I don't"
services:
  - name: memcached
    image: memcached:1.5-alpine
    ports:
      - 11211
